# (Путь к файлу должен соответствовать CONFIG_FILE_PATH в config.py,

# Настройки для голосового ассистента "Изумруд"

local: "ru-RU"

stt:
  # model_name: "ru-RU"             # Имя папки модели Vosk (например, "vosk-model-small-ru-0.22")
  model_path_base: "stt_models/"  # Базовый путь к папке с моделями STT
  samplerate: 16000
  channels: 1
  blocksize: 8000
  device_id: null                 # null или не указывать для устройства по умолчанию, или номер устройства (например, 0, 1)

activation:
  keyword: "изумруд"
  activation_sound_path: "assets/sound/bdrim.wav"
  command_sound_path: "assets/sound/snap.wav"

tts:
  language: "ru"             # Имя папки модели TTS (например, "tts_models/ru-v3")
  model_id: "v3_1_ru"
  samplerate: 48000
  device: "cpu"              # "cpu" или "cuda" для использования GPU, если доступно

command_vocabulary:
  quit:
    ru-RU:
      - "завершить работу"
      - "заверши работу"
      - "завершить сеанс"
      - "выход"
      - "выйди"
      - "закрыть программу"
    uz-UZ:
      - "toliq ish"
      - "ishni tugatish"
  repeat:
    ru-RU:
      - "повторяй"
      - "повтори"
    uz-UZ:
      - "takrorlang"
  enough:
    ru-RU:
      - "хватит"
      - "остановись"
    uz-UZ:
      - "to'xtat"
      - "stop"
  attention_one:
    ru-RU: 
      - "внимание один"
    uz-UZ: 
      - "diqqat bir"
  attention_two:
    ru-RU: 
      - "внимание два"
    uz-UZ: 
      - "diqqat ikki"
  danger_of_fire:
    ru-RU: 
      - "опасность возгорания"
      - "опасность пожара"
    uz-UZ:
      - "yong'in xavfi"
  launch_video_player:
    ru-RU:
      - "запусти плеер"
    uz-UZ:
      - "pleerni ishga tushiring"
  what_time_is:
    ru-RU:
      - "сколько времени"
      - "сколько сейчас времени"
      - "время"
    uz-UZ:
      - "hozirgi vaqt"
      - "qancha vaqt"

interactive_phrases:
  greeting:
  end_of_work:
    ru-RU: "завершаю работу"
    uz-UZ: "ishimni tugatyapman"
    # Можно добавить или изменить фразы здесь
