# (Путь к файлу должен соответствовать CONFIG_FILE_PATH в config.py,

# Настройки для голосового ассистента "Изумруд"

# local: "ru-RU"
local: "uz-UZ"

stt:
  # model_name: "ru-RU"             # Имя папки модели Vosk (например, "vosk-model-small-ru-0.22")
  model_path_base: "stt_models/"  # Базовый путь к папке с моделями STT
  samplerate: 16000
  channels: 1
  blocksize: 8000
  device_id: null                 # null или не указывать для устройства по умолчанию, или номер устройства (например, 0, 1)

activation:
  keyword: 
    ru-RU: "изумруд"
    uz-UZ: "zumrad"
  activation_sound_path: "assets/sound/bdrim.wav"
  command_sound_path: "assets/sound/snap.wav"

tts:
  language: 
    ru-RU: "ru"
    uz-UZ: "uz"
  voice:
    ru-RU: "kseniya"
    uz-UZ: "dilnavoz"
  model_id: 
    ru-RU: "v3_1_ru" # v4_ru |v3_1_ru | ru_v3 | aidar_v2
    uz-UZ: "v3_uz" # v4_uz | v3_uz | dilnavoz_v2
  model_path_base: "tts_models/"
  samplerate: 48000
  device: "cpu"       # "cpu" или "cuda" для использования GPU, если доступно

command_vocabulary:
  quit:
    ru-RU:
      - "завершить работу"
      - "заверши работу"
      - "завершить сеанс"
      - "выход"
      - "выйди"
      - "закрыть программу"
    uz-UZ:
      - "toliq ish"
      - "ishni tugatish"
  repeat:
    ru-RU:
      - "повторяй"
      - "повтори"
    uz-UZ:
      - "takrorlang"
  enough:
    ru-RU:
      - "хватит"
      - "остановись"
    uz-UZ:
      - "to'xtat"
      - "stop"
  attention_one:
    ru-RU: 
      - "внимание один"
      - "вниманию один"
    uz-UZ: 
      - "diqqat bir"
  attention_two:
    ru-RU: 
      - "внимание два"
    uz-UZ: 
      - "diqqat ikki"
  danger_of_fire:
    ru-RU: 
      - "опасность возгорания"
      - "опасность пожара"
    uz-UZ:
      - "yong'in xavfi"
  launch_video_player:
    ru-RU:
      - "запусти плеер"
    uz-UZ:
      - "pleerni ishga tushiring"
  what_time_is:
    ru-RU:
      - "сколько времени"
      - "сколько сейчас времени"
      - "время"
    uz-UZ:
      - "hozirgi vaqt"
      - "qancha vaqt"

interactive_phrases:
  greeting: 
    ru-RU: "Голосовой ассистент {activation.keyboard} приветствует вас!"
    uz-UZ: "Ovozli yordamchi {activation.keyboard} sizni kutib oladi!"
  end_of_work:
    ru-RU: "завершаю работу"
    uz-UZ: "ishimni tugatyapman"
  attention_one:
    ru-RU: "Внимание! Внимание! Персоналу цеха литья пройти в подсобное помещение. Внимание! Внимание! Персоналу цеха литья пройти в подсобное помещение."
    uz-UZ: "Diqqat! Diqqat! Quyma sexi xodimlari, yordamchi xonaga boringlar. Diqqat! Diqqat! Quyma sexi xodimlari, yordamchi xonaga boringlar."
  attention_two:
    ru-RU: "Внимание! Внимание! Угроза расплавления реактора! Внимание! Внимание! Угроза расплавления реактора!"
    uz-UZ: "Diqqat! Diqqat! Reaktorning qulashi xavfi! Diqqat! Diqqat! Reaktorning qulashi xavfi!"


